spring:
  application:
    name: mcpip
  main:
    banner-mode: off
    web-application-type: none
  ai:
    mcp:
      server:
        name: mcpip
        version: 1.0.0
        type: SYNC
        capabilities:
          completion: false
          prompt: false
        enabled: true

logging:
  pattern:
    console:
  file:
    name: C:\Users\lorda\Desktop\Pip\mcp.log

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  redirect-url: http://127.0.0.1:8080/callback
  refresh-token: ${SPOTIFY_REFRESH_TOKEN}

meme:
  save-directory: ${SAVE_DIRECTORY}

github:
  access-token: ${GITHUB_ACCESS_TOKEN}
  repository-path: ${REPOSITORY_PATH}